"""Shared constants for CTR processing services and jobs."""

DEFAULT_COMPOSE_PROJECT_NAME = "ctx_ctr"

DEFAULT_POSTGRES_DB = "ctx_ctr"
DEFAULT_POSTGRES_USER = "ctx_ctr"
DEFAULT_POSTGRES_PASSWORD = "ctx_ctr"
DEFAULT_POSTGRES_PORT = 5432

DEFAULT_REDIS_PORT = 6379

DEFAULT_KAFKA_PORT = 9092
DEFAULT_KAFKA_INTERNAL_PORT = 29092

DEFAULT_FLINK_JOBMANAGER_PORT = 8081
DEFAULT_SPARK_MASTER_WEBUI_PORT = 8080
DEFAULT_SPARK_MASTER_PORT = 7077
DEFAULT_SPARK_WORKER_WEBUI_PORT = 8082
DEFAULT_KAFKA_UI_PORT = 8088
DEFAULT_KAFKA_TOPIC_PARTITIONS = 6
DEFAULT_KAFKA_DEAD_LETTER_TOPIC_PARTITIONS = 3

DEFAULT_IMPRESSION_TOPIC = "ctr.impressions"
DEFAULT_CLICK_TOPIC = "ctr.clicks"
DEFAULT_EVENT_TOPIC = "ctr.events"
DEFAULT_DEAD_LETTER_TOPIC = "ctr.dead-letter"

DEFAULT_KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"
DEFAULT_REDIS_URL = "redis://localhost:6379/0"
DEFAULT_POSTGRES_DSN = "postgresql://ctx_ctr:ctx_ctr@localhost:5432/ctx_ctr"
DEFAULT_SPARK_MASTER_URL = "spark://localhost:7077"
DEFAULT_FLINK_REST_URL = "http://localhost:8081"
DEFAULT_FLINK_KAFKA_CONNECTOR_JAR = "jars/flink-sql-connector-kafka-3.2.0-1.19.jar"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_COLOR = "cyan"

DEFAULT_CTR_TRUST_Z_SCORE = 1.96
DEFAULT_CTR_TRUST_MIN_IMPRESSIONS = 100
DEFAULT_CTR_TRUST_MAX_VARIANCE = 0.0005
DEFAULT_CTR_TRUST_MAX_CI_WIDTH = 0.05
DEFAULT_CTR_KAFKA_STARTING_OFFSETS = "latest"
DEFAULT_CTR_METRICS_FLUSH_INTERVAL_MS = 1000

DEFAULT_WEIGHT_UPDATE_INTERVAL_SECONDS = 3600
DEFAULT_WEIGHT_UPDATE_LEARNING_RATE = 0.25
DEFAULT_WEIGHT_UPDATE_EVIDENCE_SMOOTHING = 1000.0
DEFAULT_WEIGHT_UPDATE_RIDGE = 0.01
DEFAULT_WEIGHT_UPDATE_MAX_DELTA = 0.25
DEFAULT_WEIGHT_UPDATE_MIN_FEATURE_IMPRESSIONS = 500
DEFAULT_WEIGHT_UPDATE_MAX_FEATURE_CI_WIDTH = 0.02
DEFAULT_WEIGHT_UPDATE_BASELINE_MAX_CI_WIDTH = 0.005

REDIS_CTR_KEY_PREFIX = "ctr"
REDIS_WEIGHTS_KEY_PREFIX = "weights"
REDIS_CURRENT_WEIGHTS_KEY = "weights:current"
