"""Shared environment variables loaded from `.env` with project defaults."""

from __future__ import annotations

import os

from dotenv import load_dotenv

from ctx_ctr.constants import (
    DEFAULT_CLICK_TOPIC,
    DEFAULT_COMPOSE_PROJECT_NAME,
    DEFAULT_DEAD_LETTER_TOPIC,
    DEFAULT_EVENT_TOPIC,
    DEFAULT_FLINK_JOBMANAGER_PORT,
    DEFAULT_FLINK_REST_URL,
    DEFAULT_IMPRESSION_TOPIC,
    DEFAULT_KAFKA_BOOTSTRAP_SERVERS,
    DEFAULT_KAFKA_INTERNAL_PORT,
    DEFAULT_KAFKA_PORT,
    DEFAULT_KAFKA_UI_PORT,
    DEFAULT_LOG_COLOR,
    DEFAULT_LOG_LEVEL,
    DEFAULT_POSTGRES_DB,
    DEFAULT_POSTGRES_DSN,
    DEFAULT_POSTGRES_PASSWORD,
    DEFAULT_POSTGRES_PORT,
    DEFAULT_POSTGRES_USER,
    DEFAULT_REDIS_PORT,
    DEFAULT_REDIS_URL,
    DEFAULT_SPARK_MASTER_PORT,
    DEFAULT_SPARK_MASTER_URL,
    DEFAULT_SPARK_MASTER_WEBUI_PORT,
    DEFAULT_SPARK_WORKER_WEBUI_PORT,
)

load_dotenv()

COMPOSE_PROJECT_NAME = os.getenv("COMPOSE_PROJECT_NAME", DEFAULT_COMPOSE_PROJECT_NAME)

POSTGRES_DB = os.getenv("POSTGRES_DB", DEFAULT_POSTGRES_DB)
POSTGRES_USER = os.getenv("POSTGRES_USER", DEFAULT_POSTGRES_USER)
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", DEFAULT_POSTGRES_PASSWORD)
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", str(DEFAULT_POSTGRES_PORT)))

REDIS_PORT = int(os.getenv("REDIS_PORT", str(DEFAULT_REDIS_PORT)))

KAFKA_PORT = int(os.getenv("KAFKA_PORT", str(DEFAULT_KAFKA_PORT)))
KAFKA_INTERNAL_PORT = int(os.getenv("KAFKA_INTERNAL_PORT", str(DEFAULT_KAFKA_INTERNAL_PORT)))

FLINK_JOBMANAGER_PORT = int(
    os.getenv("FLINK_JOBMANAGER_PORT", str(DEFAULT_FLINK_JOBMANAGER_PORT))
)
SPARK_MASTER_WEBUI_PORT = int(
    os.getenv("SPARK_MASTER_WEBUI_PORT", str(DEFAULT_SPARK_MASTER_WEBUI_PORT))
)
SPARK_MASTER_PORT = int(os.getenv("SPARK_MASTER_PORT", str(DEFAULT_SPARK_MASTER_PORT)))
SPARK_WORKER_WEBUI_PORT = int(
    os.getenv("SPARK_WORKER_WEBUI_PORT", str(DEFAULT_SPARK_WORKER_WEBUI_PORT))
)
KAFKA_UI_PORT = int(os.getenv("KAFKA_UI_PORT", str(DEFAULT_KAFKA_UI_PORT)))

KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    "KAFKA_BOOTSTRAP_SERVERS",
    DEFAULT_KAFKA_BOOTSTRAP_SERVERS,
)
REDIS_URL = os.getenv("REDIS_URL", DEFAULT_REDIS_URL)
POSTGRES_DSN = os.getenv("POSTGRES_DSN", DEFAULT_POSTGRES_DSN)
SPARK_MASTER_URL = os.getenv("SPARK_MASTER_URL", DEFAULT_SPARK_MASTER_URL)
FLINK_REST_URL = os.getenv("FLINK_REST_URL", DEFAULT_FLINK_REST_URL)

IMPRESSION_TOPIC = os.getenv("IMPRESSION_TOPIC", DEFAULT_IMPRESSION_TOPIC)
CLICK_TOPIC = os.getenv("CLICK_TOPIC", DEFAULT_CLICK_TOPIC)
EVENT_TOPIC = os.getenv("EVENT_TOPIC", DEFAULT_EVENT_TOPIC)
DEAD_LETTER_TOPIC = os.getenv("DEAD_LETTER_TOPIC", DEFAULT_DEAD_LETTER_TOPIC)

LOG_LEVEL = os.getenv("LOG_LEVEL", DEFAULT_LOG_LEVEL)
LOG_COLOR = os.getenv("LOG_COLOR", DEFAULT_LOG_COLOR)
